version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.9
    commands:
      - echo "Installing zip utility..."
      - yum install -y zip
      - echo "Changing into pdf_ui directory"
      - cd pdf_ui

  pre_build:
    commands:
      - echo "Installing frontend dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building React application..."
      - npm run build
      - echo "Creating deployment package..."
      - zip -r frontend.zip build/
      - echo "Frontend build completed successfully"

  post_build:
    commands:
      - echo "🚀 Deploying frontend to Amplify..."
      - STACK_NAME="CdkBackendStack"
      - echo "Extracting Amplify App ID from CloudFormation outputs..."
      - >-
        export AMPLIFY_APP_ID=$(aws cloudformation describe-stacks \
          --stack-name $STACK_NAME \
          --query 'Stacks[0].Outputs[?OutputKey==`AmplifyAppId`].OutputValue' \
          --output text)
      - |
        if [ -z "$AMPLIFY_APP_ID" ] || [ "$AMPLIFY_APP_ID" = "None" ]; then
          echo "❌ Error: Could not find AmplifyAppId in CDK stack outputs"
          echo "Available outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs'
          exit 1
        fi
      - echo "Creating Amplify deployment..."
      - >-
        aws amplify create-deployment \
          --app-id $AMPLIFY_APP_ID \
          --branch-name main \
          --output json > deployment_response.json
      - echo "Extracting upload URL and job ID..."
      - >-
        export UPLOAD_URL=$(python3 -c "import json; data=json.load(open('deployment_response.json')); print(data['zipUploadUrl'])")
      - >-
        export JOB_ID=$(python3 -c "import json; data=json.load(open('deployment_response.json')); print(data['jobId'])")
      - echo "Uploading frontend.zip to Amplify..."
      - curl -X PUT -T frontend.zip "$UPLOAD_URL"
      - echo "Starting deployment..."
      - >-
        aws amplify start-deployment \
          --app-id $AMPLIFY_APP_ID \
          --branch-name main \
          --job-id $JOB_ID
      - echo "✅ Frontend deployment initiated successfully!"
