version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing zip utility..."
      - yum install -y zip
      - echo "Retrieving deployment info from SSM Parameter Store..."
      - >-
        export AMPLIFY_APP_ID=$(aws ssm get-parameter \
          --name "/pdf-ui/$PROJECT_TIMESTAMP/amplify-app-id" \
          --query 'Parameter.Value' \
          --output text)
      - echo "Retrieved Amplify App ID: $AMPLIFY_APP_ID"
      - echo "Changing into pdf_ui directory"
      - cd pdf_ui

  pre_build:
    commands:
      - echo "Installing frontend dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building React application..."
      - npm run build
      - echo "Creating deployment package..."
      - zip -r frontend.zip build/
      - echo "Frontend build completed successfully"

  post_build:
    commands:
      - echo "🚀 Deploying frontend to Amplify..."
      - echo "Creating Amplify deployment..."
      - >-
        aws amplify create-deployment \
          --app-id $AMPLIFY_APP_ID \
          --branch-name main \
          --output json > deployment_response.json
      - echo "Extracting upload URL and job ID..."
      - >-
        export UPLOAD_URL=$(python3 -c "import json; data=json.load(open('deployment_response.json')); print(data['zipUploadUrl'])")
      - >-
        export JOB_ID=$(python3 -c "import json; data=json.load(open('deployment_response.json')); print(data['jobId'])")
      - echo "Upload URL: $UPLOAD_URL"
      - echo "Job ID: $JOB_ID"
      - echo "Uploading frontend.zip to Amplify..."
      - curl -X PUT -T frontend.zip "$UPLOAD_URL"
      - echo "Starting deployment..."
      - >-
        aws amplify start-deployment \
          --app-id $AMPLIFY_APP_ID \
          --branch-name main \
          --job-id $JOB_ID
      - echo "✅ Frontend deployment initiated successfully!"
      - echo "🌐 Your app will be available at: https://main.${AMPLIFY_APP_ID}.amplifyapp.com"
